name: "Blog of Xiaoxi Mo"
description: "Web Security Blog by Xiaoxi "

url: "http://momomoxiaoxi.com"


timezone: Asia/Shanghai

paginate: 10

paginate_path: "page:num"

highlighter: rouge

markdown:  kramdown
kramdown:
  input: GFM
  auto_ids:      true


highlighter: rouge

permalink: pretty

gems: [jekyll-paginate]

email: momomomoxiaoxi@gamil.com