name: "Blog of Xiaoxi Mo"
description: "Web Front-End Blog by Xiaoxi Mo"

url: "http://momomoxiaoxi.com"


timezone: Asia/Shanghai

paginate: 10

paginate_path: "page:num"

highlighter: pygments

markdown: rdiscount
permalink: pretty

gems: [jekyll-paginate]

email: momomomoxiaoxi@gamil.com
