name: "Blog of Xiaoxi Mo"
description: "Web Front-End Blog by Xiaoxi Mo"

url: "http://zhangwenli.com/blog"

timezone: Asia/Shanghai

paginate: 20

highlighter: pygments

markdown: rdiscount
permalink: pretty
